config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create, :destroy]
  end
 
  resources :users, only: [:index,:show,:edit,:update,:create] do
   resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
 end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  
  has_many :relationships, foreign_key: :following_id
  # フォローする側から中間テーブルへのアソシエーション
  has_many :followings, through: :relationships, source: :follower
  # フォローする側からフォローされたユーザを取得する
  
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  # フォローされる側から中間テーブルへのアソシエーション
  has_many :followers, through: :reverse_of_relationships, source: :following
  # フォローされる側からフォローしているユーザを取得する
  
  
  def following?(user)
    followings.include?(user)
    # フォロワー=followings、(user) = 1人のユーザー、includde? = 含まれているか？
  end
  
  def self.search_for(content,method)
    if method == "perfect"
      User.where(name: content)
    elsif method == "forward"
      User.where("name LIKE?", content + "%")
    elsif method == "backward"
      @user = User.where("name LIKE?", "%" + content)
    else
      User.where("name LIKE ?", "%"+ content + "%")
    end
  end
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50} 

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @users = @book.user
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
    @users_id = User.where.not(id: current_user.id)
    # idがcurrent_user.id以外全て持ってくる
    
  end
  
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        
        <td><p>フォロー数：<%= user.followings.count %></p></td>
        <td><p>フォロワー数：<%= user.followers.count %></p></td>
        <td>
          <% if current_user.following?(user) %>
          
          <%=link_to user_relationships_path(user), method: :delete do %>
            <button type="button" class="btn btn btn-danger">フォロー解除</button>
          <% end %>
          <% else %>
          <%=link_to user_relationships_path(user), method: :post do %>
            <button type="button" class="btn btn btn-primary">フォロー</button>
          <% end %>
          <!--https://www.youtube.com/watch?v=iAIRNEsA-7g　参照-->
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, followings_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to  user.followers.count, followers_user_path(user) %></th>
  </tr>
</table>
　
<div class='row'>
  <% if user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <% else %>
   <% if current_user.following?(user) %>
          
          <%=link_to user_relationships_path(user), method: :delete do %>
            <button type="button" class="btn btn btn-danger">フォロー解除</button>
          <% end %>
          <% else %>
          <%=link_to user_relationships_path(user), method: :post do %>
            <button type="button" class="btn btn btn-primary">フォロー</button>
          <% end %>
          <!--https://www.youtube.com/watch?v=iAIRNEsA-7g　参照-->
          <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th> </th>
            <th> </th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(50,50) %></td>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td><p>フォロー数：<%= user.followings.count %></p></td>
              <td><p>フォロワー数：<%= user.followers.count %></p></td>
              <td>
                <%= link_to 'Show', books_path %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/followings.html.erb
      <h1>Follow Users</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th>  </th>
            <th>  </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>   
                <%= image_tag user.get_profile_image(50,50) %>
              </td>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td><p>フォロー数：<%= user.followings.count %></p></td>
              <td><p>フォロワー数：<%= user.followers.count %></p></td>
              <td>
                <%= link_to 'Show', books_path %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
       <%= render 'books/form', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
       <%= render 'index',users: @users_id %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>